name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  FORCE_COLOR: 2

concurrency:
  group: deploy-to-neocities
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i
      - run: npm run build:neo
      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website-artifacts
          include-hidden-files: true
          path: _site
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: website-artifacts
          path: _site
      - name: List contents of the working directory
        run: ls -al
      - name: Deploy to neocities
        uses: bcomnes/deploy-to-neocities@v2
        with:
          api_token: ${{ secrets.NEOCITIES_API_TOKEN }}
          cleanup: true
          dist_dir: _site
      - name: deploy2nekoweb
        uses: deploy2nekoweb/deploy2nekoweb@v4
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-cookie: ${{ secrets.NEKOWEB_COOKIE }}
          nekoweb-folder: "site"
          directory: "_site"
